# Generated by Django 3.0.3 on 2020-06-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
