# Generated by Django 3.0.3 on 2020-06-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
