# Generated by Django 3.0.3 on 2020-06-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_question_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='slug',
            new_name='question_id',
        ),
    ]
