# Generated by Django 3.0.3 on 2020-06-16 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
